all:
	gcc -o pipe1 pipe1.c
	gcc -o pipe3 pipe3.c
	gcc -o pipe4 pipe4.c
	gcc -o twoPipesChild twoPipesChild.c
	gcc -o twoPipesParent twoPipesParent.c
	gcc -o pipeFifo pipeFifo.c

clean:
	rm pipe1 pipe3 pipe4 twoPipesChild twoPipesParent pipeFifo
