all:
	gcc -o task1 task1.c 

	gcc -o task2 task2.c 

	gcc -o task3 task3.c

	gcc -o task4 task4.c

	gcc -o task5 task5.c 

	gcc -o task6 task6.c 

	gcc -o task7 task7.c

	gcc -o task8 task8.c

	gcc -o task9 task9.c 

clean:
	rm task1 task2 task3 task4 task5 task6 task7 task8 task9