all:
	gcc -o task1 task1.c 

	gcc -o fork1 fork1.c 

	gcc -o forkWait forkWait.c

	gcc -o forkExec forkExec.c

	gcc -o task5 task5.c

	gcc -o child child.c 

clean:
	rm task1 fork1 forkWait forkExec task5 child